# Generated by Django 5.0.7 on 2024-08-04 16:15

import game_rooms.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='delete_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='id_code',
            field=game_rooms.fields.IdCodeField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='players_list',
            field=models.ManyToManyField(blank=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
